specVersion: 1.0.0
name: zoombies-subquery
version: 1.0.0
runner:
  node:
    name: "@subql/node"
    version: ">=0.35.0"
  query:
    name: "@subql/query"
    version: ">=0.16.0"
description: Zoom Token mint, burn and approvals, Zoombies NFT events on Moonriver
repository: https://github.com/ryanprice/zoombies-subquery
schema:
  file: ./schema.graphql
network:
  genesisHash: '0x401a1f9dca3da46f5c4091016c8a2f26dcea05865116b286f60f668207d1474b' # Genesis hash of Moonriver
  endpoint: "wss://moonriver.api.onfinality.io/public-ws"
  dictionary: "https://api.subquery.network/sq/subquery/moonriver-dictionary"
  chaintypes:
    file: ./dist/chaintypes.js

dataSources:
  - kind: substrate/FrontierEvm
    startBlock: 442090
    processor:
      file: ./node_modules/@subql/frontier-evm-processor/dist/bundle.js
      options:
        # Must be a key of assets
        abi: "erc20"
        address: "0x8bd5180Ccdd7AE4aF832c8C03e21Ce8484A128d4"
    assets:
      erc20:
        file: "./erc20.abi.json"
    mapping:
      file: './dist/index.js'
      handlers:
        - handler: handleMoonriverEvent
          kind: substrate/FrontierEvmEvent
          filter:
            ## Topics that follow Ethereum JSON-RPC log filters
            ## https://docs.ethers.io/v5/concepts/events/
            ## With a couple of added benefits:
            ##  - Values don't need to be 0 padded
            ##  - Event fragments can be provided and automatically converted to their id
            topics:
              ## Example valid values:
              # - '0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef'
              # - Transfer(address,address,u256)
              # - Transfer(address from,address to,uint256 value)

              ## Example of OR filter, will capture Transfer or Approval events
              # - - 'Transfer(address indexed from,address indexed to,uint256 value)'
              #   - 'Approval(address indexed owner, address indexed spender, uint256 value)'

              - Transfer(address indexed from,address indexed to,uint256 value)
              ## topics[1] to topics[3] are the indexed values
              - null
              - null
              - null
  - kind: substrate/FrontierEvm
    startBlock: 442090
    processor:
      file: './node_modules/@subql/frontier-evm-processor/dist/bundle.js'
      options:
        # Must be a key of assets
        abi: erc721
        address: "0x08716e418e68564c96b68192e985762740728018"
    assets:
      erc721:
        file: './Zoombies.json'
    mapping:
      file: './dist/index.js'
      handlers:
        # LogCardMinted(address indexed buyer, uint tokenId, uint32 indexed cardTypeId, uint editionNumber)
        - handler: handleLogCardMintedEvent
          kind: substrate/FrontierEvmEvent
          filter:
            topics:
              - LogCardMinted(address indexed buyer, uint tokenId, uint32 indexed cardTypeId, uint editionNumber)
        # LogPackOpened(address indexed buyer, uint8 rarity)
        - handler: handleLogPackOpenedEvent
          kind: substrate/FrontierEvmEvent
          filter:
            topics:
              - LogPackOpened(address indexed buyer, uint8 rarity)
        # LogSponsorReward(address sponsor, address affiliate, uint zoomReward)
        - handler: handleLogSponsorRewardEvent
          kind: substrate/FrontierEvmEvent
          filter:
            topics:
              - LogSponsorReward(address sponsor, address affiliate, uint zoomReward)
        # LogDailyReward(address player, uint newBoosterBalance)
        - handler: handleLogDailyRewardEvent
          kind: substrate/FrontierEvmEvent
          filter:
            topics:
              - LogDailyReward(address player, uint newBoosterBalance)
        # LogRewardBoosters(address winner, uint boostersAwarded)
        - handler: handleLogRewardBoostersEvent
          kind: substrate/FrontierEvmEvent
          filter:
            topics:
              - LogRewardBoosters(address winner, uint boostersAwarded)
        # LogSacrificeNFT(address owner, uint256 tokenId, uint16 cardTypeId, uint256 zoomGained)
        - handler: handleLogSacrificeNFTEvent
          kind: substrate/FrontierEvmEvent
          filter:
            topics:
              - LogSacrificeNFT(address owner, uint256 tokenId, uint16 cardTypeId, uint256 zoomGained)
        # Transfer(address indexed from, address indexed to, uint256 indexed tokenId)
        - handler: handleNFTTransferEvent
          kind: substrate/FrontierEvmEvent
          filter:
            topics:
              - Transfer(address indexed from, address indexed to, uint256 indexed tokenId)
