specVersion: 1.0.0
name: zoombies-subquery
version: 1.0.0
runner:
  node:
    name: "@subql/node"
    version: ">=0.35.0"
  query:
    name: "@subql/query"
    version: ">=0.16.0"
description: Moonbeam branch - Zoom Token mint, burn and approvals, Zoombies NFT events
repository: https://github.com/Cardinal-Entertainment/zoombies-subquery
schema:
  file: ./schema.graphql
network:
  chainId: '0xfe58ea77779b7abda7da4ec526d14db9b1e9cd40a217c34892af80a9b332b76d' # Genesis hash of Moonbeam
  endpoint: "wss://moonbeam.api.onfinality.io/ws?apikey=2c862d3c-611b-42fb-be0c-638f60da7993"
  dictionary: "https://api.subquery.network/sq/subquery/moonbeam-dictionary"
  chaintypes:
    file: ./dist/chaintypes.js

dataSources:
  - kind: substrate/FrontierEvm
    startBlock: 3355965
    processor:
      file: ./node_modules/@subql/frontier-evm-processor/dist/bundle.js
      options:
        # Must be a key of assets
        abi: "erc20"
        address: "0xc46c5cb32a72663c0db3205f6b444f9c34e216d1"
    assets:
      erc20:
        file: "./erc20.abi.json"
    mapping:
      file: './dist/index.js'
      handlers:
        - handler: handleMoonbeamEvent
          kind: substrate/FrontierEvmEvent
          filter:
            ## Topics that follow Ethereum JSON-RPC log filters
            ## https://docs.ethers.io/v5/concepts/events/
            ## With a couple of added benefits:
            ##  - Values don't need to be 0 padded
            ##  - Event fragments can be provided and automatically converted to their id
            topics:
              ## Example valid values:
              # - '0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef'
              # - Transfer(address,address,u256)
              # - Transfer(address from,address to,uint256 value)

              ## Example of OR filter, will capture Transfer or Approval events
              # - - 'Transfer(address indexed from,address indexed to,uint256 value)'
              #   - 'Approval(address indexed owner, address indexed spender, uint256 value)'

              - Transfer(address indexed from,address indexed to,uint256 value)
              ## topics[1] to topics[3] are the indexed values
              - null
              - null
              - null
  # - kind: substrate/FrontierEvm
  #   startBlock: 3355969
  #   processor:
  #     file: './node_modules/@subql/frontier-evm-processor/dist/bundle.js'
  #     options:
  #       # Must be a key of assets
  #       abi: erc721
  #       address: "0xd6E8A1d5E0675168aF078391Ec3AbD983Eb18EA0"
  #   assets:
  #     erc721:
  #       file: './Zoombies.json'
  #   mapping:
  #     file: './dist/index.js'
  #     handlers:
  #       # LogCardMinted(address indexed buyer, uint tokenId, uint32 indexed cardTypeId, uint editionNumber)
  #       - handler: handleLogCardMintedEvent
  #         kind: substrate/FrontierEvmEvent
  #         filter:
  #           topics:
  #             - LogCardMinted(address indexed buyer, uint tokenId, uint8 rarity,uint32 indexed cardTypeId, uint editionNumber, bool isFoil)
  #       # LogPackOpened(address indexed buyer, uint8 rarity)
  #       - handler: handleLogPackOpenedEvent
  #         kind: substrate/FrontierEvmEvent
  #         filter:
  #           topics:
  #             - LogPackOpened(address indexed buyer, uint8 rarity)
  #       # LogSponsorReward(address sponsor, address affiliate, uint zoomReward)
  #       - handler: handleLogSponsorRewardEvent
  #         kind: substrate/FrontierEvmEvent
  #         filter:
  #           topics:
  #             - LogSponsorReward(address sponsor, address affiliate, uint zoomReward)
  #       # LogDailyReward(address player, uint newBoosterBalance)
  #       - handler: handleLogDailyRewardEvent
  #         kind: substrate/FrontierEvmEvent
  #         filter:
  #           topics:
  #             - LogDailyReward(address player, uint newBoosterBalance)
  #       # LogRewardBoosters(address winner, uint boostersAwarded)
  #       - handler: handleLogRewardBoostersEvent
  #         kind: substrate/FrontierEvmEvent
  #         filter:
  #           topics:
  #             - LogRewardBoosters(address winner, uint boostersAwarded)
  #       # LogSacrificeNFT(address owner, uint256 tokenId, uint16 cardTypeId, uint256 zoomGained)
  #       - handler: handleLogSacrificeNFTEvent
  #         kind: substrate/FrontierEvmEvent
  #         filter:
  #           topics:
  #             - LogSacrificeNFT(address owner, uint256 tokenId, uint16 cardTypeId, uint256 zoomGained)
  #       # Transfer(address indexed from, address indexed to, uint256 indexed tokenId)
  #       - handler: handleNFTTransferEvent
  #         kind: substrate/FrontierEvmEvent
  #         filter:
  #           topics:
  #             - Transfer(address indexed from, address indexed to, uint256 indexed tokenId)
